jQuery(function(){var gifs=[];var gif_urls=[];var player_wrap=jQuery('.gif_wrap');var showing_btn=jQuery('span.play_gif');var playing=!1;var first_load=!0;var stop_load=!1;var last_viewed=null;var spinnerPreload;var spinnerLoading;var spinnerOptions={lines:13,length:12,width:8,radius:18,trail:100,speed:1.3,color:'#fff',className:'gif_spinner'};spinnerPreload=new Spinner(spinnerOptions);spinnerLoading=new Spinner(spinnerOptions);function preload_gif(url,idx){if(!gifs[idx]){var img=new Image();img.src=url;img.className='_showing';gifs[idx]=img;first_load=!0;return img}else{first_load=!1;return gifs[idx]}}
jQuery('._showing.frame').each(function(){var s=jQuery(this);if(s.attr('src')){if(s.attr('data-lazy-src')){gif_urls.push(s.attr('data-lazy-src').replace('_still_tmp.jpeg','.gif'))}else{if(typeof s.attr('src')!=='undefined'&&s.attr('src')!==!1){gif_urls.push(s.attr('src').replace('_still_tmp.jpeg','.gif'))}else{gif_urls.push(s.src.replace('_still_tmp.jpeg','.gif'))}}}else if(s.data('cfsrc')){gif_urls.push(s.data('cfsrc').replace('_still_tmp.jpeg','.gif'))}});jQuery(document).ready(function(){spinnerPreload.spin();if(jQuery('.gif_wrap').length){jQuery('.gif_wrap')[0].appendChild(spinnerPreload.el)}});jQuery(window).on('load',function(){spinnerPreload.stop();var showing_btn_idx="";var gif_img;var displayedImgSrc;var hiddenImgSrc;showing_btn.css('visibility','visible');function play(idx){displayedImgSrc=jQuery('._showing')[idx].src;hiddenImgSrc=jQuery('._hidden')[idx].src;last_viewed=idx;showing_btn_idx=showing_btn[idx];if(playing==!1){playing=!0;showing_btn_idx.style.visibility='hidden'}else{playing=!1;showing_btn_idx.style.visibility='visible'}
if(displayedImgSrc==gifs[idx].src&&!first_load){displayedImgSrc=hiddenImgSrc;hiddenImgSrc=gifs[idx].src;if(playing==!1)
last_viewed=null;else last_viewed=idx}else if(hiddenImgSrc==gifs[idx].src){hiddenImgSrc=displayedImgSrc;displayedImgSrc=gifs[idx].src}
jQuery('._showing')[idx].src=displayedImgSrc;jQuery('._hidden')[idx].src=hiddenImgSrc}
jQuery('.gif_wrap').click(function(event){var self=this;var idx=jQuery('.gif_wrap').index(this);if(!gifs[idx]){first_load=!0;spinnerLoading.spin();self.appendChild(spinnerLoading.el)}
if(first_load){stop_load=!0;gif_img=preload_gif(gif_urls[idx],idx);gif_img.onload=function(){spinnerLoading.stop();first_load=!1};jQuery(self).children('img').attr('src',gif_img.src)}
if(!last_viewed&&last_viewed!=0){last_viewed=idx}
if(idx==last_viewed){play(idx)}else{if(playing){showing_btn_idx=showing_btn[last_viewed];showing_btn_idx.style.visibility='visible';if(jQuery('._showing')[last_viewed].src==gifs[last_viewed].src){var tmpSrc=jQuery('._showing')[last_viewed].src;jQuery('._showing')[last_viewed].src=jQuery('._hidden')[last_viewed].src;jQuery('._hidden')[last_viewed].src=tmpSrc}
playing=!1;play(idx)}}});player_wrap.mouseenter(function(){player_wrap.css('cursor','pointer')})})})